export type SchemaModels =
  | 'users'
  | 'residents'
  | 'employees'
  | 'maintenanceRequests'
  | 'complaints'
  | 'payments'
  | 'announcements'
  | 'forumPosts'
  | 'postTags'
  | 'forumComments'
  | 'leases'
  | 'bills'
  | 'units'
  | 'contacts';
